### ISSUE TITLE
JCOW404.key unable to decrypt my enc file

### ISSUE THREAD

**Issue by akiratoriyama** [itsyourap/JioFiber-Home-Gateway#11]
OpenSSL gives the following error

*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
20080000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers\implementations\ciphers\ciphercommon_block.c:124:

**Comment by itsyourap** [comment]
Can you tell me your firmware version?

**Comment by Ghost-Rider10** [comment]
Same Problem But Terminal Give Different Output.

![Error](https://user-images.githubusercontent.com/45249429/178526283-793c874f-09e2-4899-b4cb-aa2c026e8acf.png)

**Comment by itsyourap** [comment]
Yes! The encryption password changed in the latest firmwares. Basically now the encryption key is specific for specific devices. The encryption key is a mixture of our router's serial number concatenated with the output of the command `/usr/bin/prolinecmd acspwd display`. Since the value of `acspwd` is unique for every device, I assume that there is no way to get root for now.

**Comment by itsyourap** [comment]
Also the first five characters of `acspwd` matches the last five characters of your default Wi-Fi SSID name. I don't know about the origin of the next eleven characters. 

For example, if your default SSID is `JioFiber-XrHGa`, the first five characters of `acspwd` is `XrHGa`.

**Comment by itsyourap** [comment]
**There is a solution to this**  🎊 

Use the WEB-UI to downgrade your router firmware to a version that used to work with this method.

**Comment by neelahagga** [comment]
> Use the WEB-UI to downgrade your router firmware to a version that used to work with this method.

Where can I find such a version for JCO4032?

**Comment by itsyourap** [comment]
@neelahagga Idk- I didn't get a firmware for JCO4032 yet

**Comment by itsyourap** [comment]
Use this to get Root: 
https://github.com/itsyourap/JioFiber-Home-Gateway/blob/master/Instructions/Alternate-Way-To-Get-Root-Access-JioFiber-ONT-Home-Gateway.md
