### ISSUE TITLE
Decryption is not succesfull

### ISSUE THREAD

**Issue by Arkduke** [itsyourap/JioFiber-Home-Gateway#13]
after using openssl to decrypt using the provided key file the file generated cosists of some chinese symbol and in the console its throwing message of bad decrypt. I am having router of firmware SRCMTF1_JCOW414_R2.41
![image](https://user-images.githubusercontent.com/55138490/197565832-1776cf13-3444-4757-bbfa-04645320d668.png)

**Comment by itsyourap** [comment]
`R2.39` has introduced a device-specific way of encryption, which means that universal decryption isn't going to work. Currently, I don't have a way to get root access to firmware with versions `R2.39` and later.

**Comment by Arkduke** [comment]
Okay then, i have to add another router🥲🥲.

**Comment by itsyourap** [comment]
Please Check:
https://github.com/itsyourap/JioFiber-Home-Gateway/blob/master/Instructions/Alternate-Way-To-Get-Root-Access-JioFiber-ONT-Home-Gateway.md
