### ISSUE TITLE
not able to decrypt using the key from /flash/secure/key.txt

### ISSUE THREAD

**Issue by tanishqjasoria** [itsyourap/JioFiber-Home-Gateway#19]
I got the key: RRIOTJI00000524XXXXXXXXXXXXXXXXXXXXXXXXXXXX (<serial_number><32 char string>)
then i used this command to decrypt the back up file: 
`openssl aes-128-cbc -d -pass file:key.txt -in RRIOTJI00000524_JCOW411.enc -out RRIOTJI00000524_JCOW411.txt `
`openssl aes-128-cbc -d -md md5 -pass file:key.txt -in RRIOTJI00000524_JCOW411.enc -out RRIOTJI00000524_JCOW411.txt `
had the same error
```*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
4087D438AD7F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../providers/implementations/ciphers/ciphercommon_block.c:124:
```
`OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
`

**Comment by tanishqjasoria** [comment]
apparently it was not needed - found the server.key in the firmware and it decrypted using that

**Comment by itsyourap** [comment]
Can you tell me your Router Firmware version?

**Comment by tanishqjasoria** [comment]
ARCNTF1_JCOW411_R2.21

**Comment by itsyourap** [comment]
Completed via Telegram DMs

**Comment by Gangadhararao29** [comment]
I am also facing the same issue , I got the secret file but decreption is failing

**Comment by itsyourap** [comment]
> I am also facing the same issue , I got the secret file but decreption is failing

@Gangadhararao29 Please tell me your firmware version

**Comment by Gangadhararao29** [comment]
@itsyourap JCOW414 v2.49

**Comment by itsyourap** [comment]
> @itsyourap JCOW414 v2.49

@Gangadhararao29 You can definitely downgrade your firmware from the WEB-UI and get root if you want.
