### ISSUE TITLE
Use gpon for our own use

### ISSUE THREAD

**Issue by adbishnoi507** [itsyourap/JioFiber-Home-Gateway#25]
I have done the telnet part. And got access to it. 

I wanna use this as my own modem as my isp modem sucks 
My isp requires a vlan id of 528 and a pppoe username and password

I have tried configuring .enc and flashing it with no success. 

Any ways i can do this.

**Comment by adbishnoi507** [comment]
How can i flash old firmware ? 
I have img file but what about the key?

**Comment by xtendtech** [comment]
cant you find it in this github repo?

**Comment by AG4lyf** [comment]
do you know the exact version ? 
we went to R1.12. and it is now bad cipher. 

```bad decrypt
74560100:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers\implementations\ciphers\ciphercommon_block.c:124:```

**Comment by AG4lyf** [comment]
2.2 also having the same issue.

**Comment by xtendtech** [comment]
i think it might be the key  which they posted might have changed.. check the way to get root and try to copy it from the router and then use it
