### ISSUE TITLE
Running bash on router?

### ISSUE THREAD

**Issue by Celibistrial** [itsyourap/JioFiber-Home-Gateway#28]
This is a bit farfetched but is it possible to get bash running on JioFiber? 
I tried using a bash build for MIPS but it doesn't run.
I'm thinking of maybe running a small bash script on the router (uses less than 10 MB of ram and doesn't require much CPU either so it should be possible) 

Thank you for your hard work.

**Comment by itsyourap** [comment]
You need the build root source code for this. I don't know where to find it but it is with Jio.
