### ISSUE TITLE
[help wanted] Failed to update configuration (checksum error)

### ISSUE THREAD

**Issue by KngKong** [itsyourap/JioFiber-Home-Gateway#3]
I tried enabling FTP in my JioFiber following your steps,
While restoring it gives me checksum error even though i changed `config.checksum = "0"` in my decrypted file and continued.

My router description : 
    Model : JCO4032
    Firmware : SRCMTF1_JCO4032_R2.35

**Comment by itsyourap** [comment]
The ```config.checksum = "0"``` was a bug (maybe intentional) and has been fixed in R2.35 firmware. 

FTP will not work after R2.35 firmwares.

**Comment by KngKong** [comment]
@itsyourap  Is there any other way to use the FTP.

**Comment by KngKong** [comment]
Is there any other way to enable FTP in R2.35. Any other ways like downgrading the firmware or so...

**Comment by itsyourap** [comment]
Yes! I have updated my repository! Please check
