### ISSUE TITLE
how to enable ipv6 portfowarding with api

### ISSUE THREAD

**Issue by hhp-the-maestro** [itsyourap/JioFiber-Home-Gateway#8]
I have a jio fibre router, as it does not support ipv4,  i want to do it with ipv6. how to do it,  can you help me with that.

**Comment by itsyourap** [comment]
Use your IPv6 to access it

**Comment by itsyourap** [comment]
What exactly you want to do?

**Comment by hhp-the-maestro** [comment]
i want to port forward using my public ipv6 so that i must be able to access it from other networks.

**Comment by itsyourap** [comment]
Check [this repo](https://github.com/test2a/JioFiberwebhosting)
